const TICKET_TYPE_SCHEMA = `
  CREATE TABLE IF NOT EXISTS tbl_kp_tickets(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "categoryName" VARCHAR(255) NOT NULL,
    "description" VARCHAR(255),
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
  )
`;
module.exports = TICKET_TYPE_SCHEMA;
